
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[518] =
    {   0,
       57,   57,   60,   58,   56,   56,   58,   56,   48,   58,
        4,   58,   46,   49,   58,   14,   46,   46,   12,   46,
       17,   46,   50,   13,   11,   42,   43,   42,   19,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       16,   49,   10,   15,   49,   56,   57,   42,    0,   54,
        0,    4,    9,    9,    9,    9,    9,    9,    9,   44,
       47,    0,   54,    0,   46,   45,   18,    0,    3,    0,
       50,   49,   42,    0,   42,   37,    2,   55,   55,   55,
       55,   55,    8,   55,   55,   55,   55,   55,   55,   55,

       32,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   22,   55,   55,   55,   55,   55,   55,
       55,    8,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   41,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    0,    0,    3,   51,    0,   55,
        8,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   33,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,    8,   55,   55,   55,   55,   55,   55,   55,

       55,   55,   55,   55,    8,   55,    8,    8,   55,    8,
       55,   55,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    0,    5,    0,   55,   55,   55,
       55,   26,   55,   55,   55,   55,   55,   55,   55,   55,
        0,    8,   24,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,    8,   55,   55,
       55,   55,   55,   55,   55,   53,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   52,   55,   55,   55,
       55,    7,    7,    9,    9,    9,    9,    9,    6,    9,
        6,    9,    9,    9,    9,    0,    0,    1,   55,   55,

       27,   55,    8,    8,    8,   21,   55,   55,   55,   55,
        8,   55,   55,   55,   55,   29,   55,   55,    0,    0,
       55,   52,    8,   55,   55,   55,   55,   55,   55,   55,
       55,   55,    0,   55,    8,   55,   55,   55,   55,   55,
       55,   55,    8,    8,   55,   30,    8,   55,    9,    9,
        9,    9,    9,    9,    6,    9,    9,    9,   55,    0,
       55,   55,   55,   55,   20,   23,    0,   55,   34,   55,
       55,   55,   55,   55,   55,    8,   55,   55,   55,   55,
       55,    0,   55,   55,   55,    8,   55,   40,    8,   25,
        0,   55,    9,    9,    9,    9,    9,    6,    9,    9,

        9,   55,   55,   55,    8,    8,   55,   55,   55,   55,
        8,    8,   35,   55,   55,   38,   55,   55,   55,   55,
        8,   55,   38,   55,    6,    9,    9,    9,    9,    6,
        9,    6,    9,    8,    8,   39,   55,   55,   55,   31,
        8,   55,   55,   55,   55,   55,   55,   55,   55,   55,
        9,    9,    9,    9,    6,    6,   55,   55,   28,   55,
       55,   55,    8,    8,    8,    8,   55,   55,    9,    9,
        9,    9,    8,   36,    8,   55,    8,   55,   55,    9,
        9,    9,    0,   55,   55,   55,    9,    9,    9,    0,
        8,    8,   55,    9,    9,    7,    0,    0,   55,    9,

        9,   55,    9,    9,   55,    9,    9,    0,    9,    9,
        9,    9,    6,    9,    9,    7,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   37,
       53,   54,   55,   56,   57,    1,   58,   59,   60,   61,

       62,   63,   64,   65,   66,   37,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
       81,   37,   82,   83,   84,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[85] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    4,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[531] =
    {   0,
        0,    0,  364, 2019,   83,   87,  360,   91,  337,   80,
        0,   63,  329,  342,   87, 2019,   80,   84, 2019,   85,
      324,   87,   92, 2019, 2019,   90,   93,   97,  317,  103,
      108,  112,  110,  163,  158,  117,  104,  204,  109,  198,
      177,  221,  196,  142,  219,  231,  242,  192,  226,  250,
     2019, 2019,  134, 2019,  254,  205, 2019,  310,  136,  278,
      304,    0,  260,  261,  264,  266,  273,  283,  325, 2019,
     2019,  114, 2019,    0, 2019, 2019, 2019,  314,    0,  289,
      176, 2019, 2019,  115,  277, 2019, 2019,  268,  269,  290,
      291,  299,  270,  271,  318,  345,  348,  353,  365,  346,

      303,  372,  358,  375,  320,  388,  391,  396,  393,  409,
      403,  419,  405,  415,  422,  428,  434,  438,  430,  421,
      468,  420,  472,  476,  471,  491,  465,  485,  506,  475,
      505,  495,  520,  525,  534,  496,  536, 2019,  503,  518,
      540,  524,  552,  551,  557,  555,  559,  563,  569,  567,
      574,  571,  586,  590,  281,  181,    0,  241,  174,  598,
      568,  609,  623,  596,  600,  619,  625,  620,  637,  629,
      657,  652,  649,  667,  651,  671,  648,  654,  701,  697,
      668,  717,  710,  718,  714,  721,  723,  736,  744,  752,
      740,  760,  581,  743,  745,  748,  769,  777,  782,  786,

      789,  778,  806,  819,  638,  820,  698,  731,  811,  747,
      817,  800,  834,  840,  823,  810,  850,  854,  849,  863,
      857,  867,  865,  872,  244, 2019,  193,  887,  882,  898,
      832,  866,  880,  884,  919,  907,  914,  928,  895,  927,
      234,  905,  937,  936,  945,  948,  949,  939,  957,  954,
      966,  974,  977,  989,  980,  978,  992,  970, 1008,  995,
     1027,  979, 1011, 1020, 1005, 1009, 1024, 1035, 1046, 1039,
     1040, 1053, 1052, 1065, 1062, 1069, 1058, 1073, 1081, 1083,
     1078, 1080, 1090, 1100, 1102, 1110, 1103, 1112, 1108, 1130,
     1111, 1131, 1113, 1132, 1118,  196,  294, 2019, 1145, 1142,

     1155, 1162, 1159, 1161, 1163, 1165, 1173, 1179, 1174, 1176,
     2019, 1184, 1183, 1202, 1180, 1177, 1208, 1214,  191,  157,
     1218, 1188, 1225, 1227, 1231, 1234, 1237, 1235, 1242, 1257,
     1248, 1247,  150, 1265, 1194, 1269, 1268, 1279, 1274, 1286,
     1300, 1289, 1292, 1296, 1319, 1302, 1308, 1314, 1312, 1313,
     1317, 1321, 1343, 1320, 1326, 1354, 1360, 1363, 1364,  143,
     1368, 1375, 1376, 1380, 1346, 1347,  136, 1389, 1398, 1392,
     1405, 1394, 1391, 1410, 1393, 1377, 1421, 1433, 1440, 1445,
     1453,  133, 1456, 1450, 1442, 1384, 1459, 1437, 1458, 1465,
      125, 1466, 1471, 1477, 1475, 1480, 1504, 1467, 1483, 1506,

     1510, 1512, 1521, 1522, 1487, 1517, 1529, 1543, 1535, 1541,
     1520, 1539, 1547, 1549, 1561, 1551, 1573, 1555, 1586, 1590,
     1564, 1592, 1568, 1602, 1570, 1572, 1588, 1596, 1607, 1615,
     1619, 1616, 1620, 1621, 1623, 1627, 1634, 1644, 1635, 1631,
     1636, 1639, 1660, 1661, 1650, 1666, 1673, 1668, 1685, 1691,
     1654, 1693, 1664, 1698, 1689, 1695, 1719, 1718, 1701, 1703,
     1716, 1733, 1713, 1720, 1722, 1723, 1743, 1742, 1746, 1750,
     1747, 1738, 1740, 1748, 1751, 1772, 1767, 1780, 1777, 1773,
     1785, 1793,  124, 1791, 1801, 1807, 1810, 1814, 1817,  226,
     1788, 1804, 1815, 1831, 1825, 1820,  307,    0, 1838, 1841,

     1844, 1845, 1848, 1859, 1863, 1865, 1871,   90, 1870, 1878,
     1883, 1887, 1875, 1893, 1892, 1894, 2019, 1966, 1971,   96,
     1976, 1979, 1982, 1985, 1988, 1993, 1998, 2003, 2008, 2013
    } ;

static yyconst flex_int16_t yy_def[531] =
    {   0,
      517,    1,  517,  517,  517,  517,  517,  517,  517,  518,
      519,  520,  517,  517,  521,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      517,  517,  523,  517,  517,  517,  517,  517,  518,  517,
      518,  519,  524,  524,  524,  524,  524,  524,  525,  517,
      517,  521,  517,  521,  517,  517,  517,  526,  527,  517,
      517,  517,  517,  517,  517,  517,  517,  523,  522,  522,
      522,  522,  522,  523,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  523,  523,  517,  525,  524,
      524,  525,  524,  524,  524,  524,  525,  525,  525,  525,
      525,  525,  525,  525,  526,  528,  527,  517,  517,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  523,  524,  524,  524,  524,  524,  525,  525,  525,
      525,  525,  525,  525,  529,  517,  517,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      517,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      523,  524,  524,  524,  524,  525,  524,  525,  525,  525,
      525,  525,  525,  525,  525,  529,  528,  517,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      517,  522,  522,  522,  522,  522,  522,  522,  517,  517,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  517,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  523,  524,  525,
      525,  524,  525,  525,  525,  525,  525,  525,  522,  517,
      522,  522,  522,  522,  522,  522,  517,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  517,  522,  522,  522,  522,  522,  522,  522,  522,
      517,  523,  524,  525,  525,  524,  525,  525,  525,  525,

      525,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  523,  524,  525,  525,  525,  524,  525,
      525,  525,  525,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  523,  522,  522,  522,  522,  522,  523,  523,
      525,  525,  525,  524,  525,  525,  522,  522,  522,  522,
      523,  522,  522,  522,  522,  522,  523,  523,  525,  525,
      525,  524,  522,  522,  522,  523,  522,  523,  523,  525,
      525,  525,  517,  523,  523,  523,  525,  525,  525,  530,
      523,  523,  523,  525,  525,  525,  530,  530,  523,  525,

      525,  523,  525,  525,  523,  525,  525,  517,  525,  525,
      525,  525,  525,  525,  525,  525,    0,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517
    } ;

static yyconst flex_uint16_t yy_nxt[2104] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   37,   37,   39,   37,
       40,   41,   42,   37,   43,   44,   45,   46,   47,   48,
       49,   50,   51,    4,   51,   52,   53,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   37,   39,   37,   40,
       41,   42,   37,   43,   44,   45,   46,   47,   48,   49,
       50,   54,   55,   54,   56,   56,   60,   56,   56,   56,
       63,   56,   56,   56,   75,   56,   65,   66,   73,   76,

       64,   78,   76,  311,   70,   67,   79,   68,   70,   70,
       80,   70,   81,   82,   83,   83,   84,   85,   86,   69,
       63,   83,   82,   88,   88,   73,   65,   66,   88,   88,
       88,   90,   88,   61,   67,  490,   68,   88,  311,   96,
       74,   99,   60,   91,  118,  100,  311,   92,   93,  311,
       97,  101,   95,   98,   88,  112,  311,  159,  113,   94,
       94,   90,   88,  311,   94,   94,   94,   74,   94,   96,
      311,   99,   91,   94,  118,  100,   92,   93,   88,   97,
      101,   95,   98,   88,  112,  108,  159,  113,  126,   61,
      137,  127,  102,  109,   80,  156,   81,   88,   94,  110,

      226,  103,  104,  105,  311,  111,   56,   56,  227,   56,
      297,  106,   88,  107,   94,  108,   88,  126,   88,   94,
      127,  122,  102,  109,   88,  119,  133,  125,  110,  120,
      103,  104,  105,   94,  111,  298,  114,  138,  227,   88,
      106,   88,  107,  115,  116,  121,   88,  311,   94,  117,
      122,   88,   94,  128,   94,  119,  133,  125,  297,  120,
       94,  158,   88,  129,  298,  123,  114,  134,  124,  132,
       88,  130,  115,  116,  121,   94,  131,   94,  117,  498,
      139,  139,   94,  128,  139,  135,  139,   94,   88,   88,
       88,   88,  129,  139,  123,  156,  134,  124,   94,  132,

      130,   83,  143,  139,  141,  131,   94,  145,  297,  158,
       88,   88,  144,  226,  146,  135,  142,  142,  138,   88,
      142,  161,  142,   88,   94,   94,   94,   94,  156,  142,
       59,  143,  138,  141,   83,  160,   71,  145,   88,  142,
       88,  144,   87,  162,  146,  139,   94,   94,   77,  163,
      176,  161,   71,   70,  148,   94,  149,  150,  151,   94,
      498,   58,   57,  517,  160,   88,   88,  152,   88,  153,
      154,  517,  162,   88,   94,  167,   94,  172,   88,  163,
      176,  142,  517,  164,  148,   88,  149,  150,  151,  168,
      165,  166,   88,  169,  170,   88,  152,  171,  153,  154,

      517,   94,   94,  174,   94,  167,  173,  172,   88,   94,
      517,   88,  164,   88,   94,  177,   88,  175,  168,  165,
      166,   94,  169,   88,  170,   88,  178,  171,   94,   88,
      517,   94,  174,  181,  180,   88,  173,  179,  517,   88,
       88,   88,   88,  183,   94,  177,  175,   94,   88,   94,
       88,  185,   94,  182,   88,  517,  178,  187,   88,   94,
      184,   94,  181,  180,  186,   94,  179,  517,  517,  192,
      193,   94,  183,  188,  189,   94,   94,   94,   94,  190,
      185,  517,  182,  191,   94,   88,   94,  187,   88,  184,
       94,   88,   88,  186,   94,   88,   88,  517,  192,  193,

      201,  517,  188,  189,  197,   88,  194,  195,  190,  517,
      517,   88,  191,  196,  198,   88,   88,  199,  200,  517,
      206,   94,  517,  139,   94,   88,   88,   94,   94,  202,
      201,   94,   94,  203,  197,  194,  207,  195,  139,  208,
       88,   94,  196,  198,  139,   88,  199,   94,  200,  206,
      517,   94,   94,  204,   88,  209,   88,  205,  202,  142,
      139,   94,   94,  203,  517,  211,  207,  517,  208,  210,
      212,  139,  139,  213,  142,  139,   94,  139,  517,  139,
      142,   94,  204,  139,  217,  209,  205,  139,   88,  139,
       94,  139,   94,  214,  139,  211,  142,  215,  210,  216,

      212,   88,  220,  213,  218,  221,  139,  142,  142,  219,
      139,  142,  222,  142,  217,  142,   88,  223,   88,  142,
       88,  224,  214,  142,   94,  142,  215,  142,  216,   88,
      142,  232,  220,  218,  231,  221,  229,   94,  219,   88,
       88,  222,  142,   88,  228,   88,  142,  223,  233,   88,
      230,  224,   94,  517,   94,  517,   94,   88,   88,  517,
      235,  232,  517,  231,  241,   94,  229,  238,   88,   88,
      234,   88,   88,  228,   88,   94,   94,   88,  233,   94,
      230,   94,  236,  237,  239,   94,  250,   88,   88,  235,
      242,   88,  240,   94,   94,  254,  238,  244,  243,  234,

      251,  245,  517,  246,   94,   94,  247,   94,   94,  517,
       94,  236,  237,   94,  239,  250,  248,   88,   88,  242,
      249,   88,  240,   94,   94,  254,  244,   94,  243,  251,
       88,  245,  252,  246,   88,  517,  247,   88,   88,  256,
      517,   88,  253,   88,  517,  248,  257,  517,  255,  249,
      517,   88,  517,   94,   94,  258,   88,   94,  517,  259,
       88,  260,  252,   88,   88,   88,   94,   88,   88,  256,
       94,  253,   88,   94,   94,  262,  257,   94,  255,   94,
       88,  266,  261,  263,  258,  267,  264,   94,  259,   88,
      260,  265,   94,  268,  269,  517,   94,   88,   88,   94,

       94,   94,   88,   94,   94,  262,   88,  270,   94,   88,
      266,  261,  517,  263,  267,  264,   94,  517,  517,  275,
       88,  265,  268,  269,  271,   94,   88,  281,  517,  272,
      139,   88,  273,   94,   94,  274,  270,   88,   94,   88,
       88,  276,   94,  139,  517,   94,  517,  517,  275,  279,
      277,  278,   88,  271,  139,  280,   94,  281,  272,  302,
      139,  273,   94,  282,  274,  285,  286,   94,  284,  139,
      139,  276,  517,   94,  139,   94,   94,  139,  279,  142,
      277,  278,  283,  139,  280,  139,   88,  139,   94,  302,
      142,  287,  139,  282,  285,  288,  142,  289,  284,  517,

       88,  290,   88,  291,   88,  142,  142,   88,  293,  517,
      142,  283,  292,  142,  303,   88,  294,  295,   88,  142,
      287,  142,   94,  142,  288,   88,  289,   88,  142,  304,
      290,  299,  291,  300,   88,  301,   94,  293,   94,   88,
       94,  292,  309,   94,  303,  294,  295,   88,   88,  307,
      305,   94,  517,  306,   94,  308,   88,   88,  304,   88,
      299,   94,  300,   94,  301,   88,  319,  310,   88,   88,
       94,  309,  312,  517,   88,   94,  314,   88,  320,  307,
      305,  316,  306,   94,   94,  308,   88,  313,  317,  315,
       88,  318,   94,   94,   88,   94,  310,   88,   88,   88,

       88,   94,  312,  517,   94,   94,  314,  324,  322,   88,
       94,  316,   88,   94,  321,   88,  313,  317,  315,  326,
      517,  318,   94,  331,  325,   88,   94,  323,   88,   88,
       94,   88,  333,   94,   94,   94,   94,  324,  322,  327,
       88,  517,  328,  321,   88,   94,  517,   88,   94,  326,
      334,   94,  331,  325,  329,   88,  323,  332,  330,   88,
       88,   94,  336,  517,   94,   94,   88,   94,  517,  327,
      335,  328,   88,   88,  338,  339,   94,  337,   88,  334,
       94,  517,   88,   94,  329,   88,  332,  341,  330,   88,
      517,   94,  336,   88,  342,   94,   94,  340,   88,  335,

      139,   88,   94,   88,  338,  339,  517,  337,   94,   94,
      139,  343,  346,  347,   94,  344,  348,  341,   94,  345,
      139,   94,  139,  139,  342,   94,  340,  349,  139,   94,
      139,  139,  139,  139,   94,  517,  142,   94,  139,   94,
      343,  351,  346,  347,  344,  348,  142,  352,  345,  353,
      139,  139,  139,  517,  360,  517,  142,  349,  350,  142,
      356,  354,   88,  358,  142,   88,  142,  142,  142,  142,
      517,  351,  359,  517,  142,   88,  352,  355,  353,   88,
      357,   88,   88,   88,  517,   88,  142,  142,  142,  356,
      361,  354,  358,   88,   88,  367,   88,   88,   94,   88,

       88,   94,  359,   88,   88,  517,  355,  365,   88,  357,
      517,   94,  364,  362,   88,   94,  366,   94,   94,   94,
      361,   94,   88,  363,  369,  517,  517,  517,   88,   94,
       94,  368,   94,   94,   88,   94,   94,  365,   88,   94,
       94,  364,  362,  370,   94,   88,  366,   88,  372,  371,
       94,   88,  363,  369,   88,   88,  374,   88,   94,  382,
      517,  368,   88,  373,   94,  378,  375,   88,   88,  517,
       94,  517,  376,  370,   94,  517,  377,   88,  372,  371,
      381,   94,  379,   94,  380,   88,  374,   94,   88,   88,
       94,   94,  373,   94,   88,  378,  375,  385,   94,   88,

      517,  376,  517,   94,   94,  377,   88,  383,  386,   88,
      381,  379,   88,   94,  380,  384,   88,  517,  387,  517,
       88,   94,   88,  390,   94,   94,  388,  385,   88,  389,
       94,  391,  139,  139,   88,   94,  383,  139,  386,   88,
      139,  139,   94,  517,  384,   94,  139,  387,   94,  517,
      393,  396,   94,  390,  517,  388,   94,  394,   94,  389,
      392,  395,  517,  139,   94,  398,   88,   88,  142,  142,
       94,  517,  517,  142,  139,   94,  142,  142,  397,  393,
      139,  396,  142,  139,   88,  399,  394,  517,   88,  392,
      395,  400,  517,  402,  398,   88,   88,   88,  401,  142,

       88,  517,   94,   94,   88,  517,  403,  405,  397,   88,
      142,   88,   88,   88,   88,  399,  142,  517,   88,  142,
       94,  400,  404,  402,   94,   88,  406,  407,  401,  408,
       88,   94,   94,   94,  414,  403,   94,  405,  409,  411,
       94,   88,  412,  410,  413,   94,  517,   94,   94,   94,
       94,  404,  415,   88,   94,  406,  407,   88,  517,  408,
       88,   94,   88,  414,  416,   88,   94,  409,  411,  417,
       88,  412,  410,   88,  413,  418,   88,   94,   88,   88,
      419,  421,  415,  420,  517,   88,   88,  139,  422,   94,
      423,  139,  517,   94,  416,  139,   94,  139,   94,  417,

      139,   94,  517,  139,  426,  418,   94,   88,  427,   94,
      419,  421,   94,  420,   94,   94,  425,  422,  517,  428,
      423,   94,  424,  142,  139,  429,  139,  142,  431,  517,
      139,  142,   88,  142,  426,  430,  142,   88,  427,  142,
       88,   88,   88,   94,  517,  425,  517,  517,  428,   88,
      432,  433,  435,  436,  429,   88,  437,  431,  434,   88,
      142,   88,  142,   88,  439,  430,  142,   88,   94,   88,
      438,   88,  440,   94,  517,   88,   94,   94,   94,  432,
      433,   88,  435,  436,   88,   94,  437,  434,   88,  441,
      139,   94,  139,   88,  439,   94,  445,   94,  517,   94,

      438,  442,  440,   94,  444,   94,   88,  443,  139,  517,
       88,   94,   88,  517,  517,  446,  139,   94,  441,  447,
       94,  451,   88,  448,  449,  445,  142,  139,  142,   94,
      442,  450,  517,  452,  444,  139,  139,  453,  454,  139,
      139,   88,   94,   88,  142,  446,   94,   88,   94,  447,
      451,   88,  142,  448,   88,   88,   88,  517,   94,   88,
      456,  450,  452,  142,   88,  455,  453,  517,  454,  459,
       88,  142,  142,  458,  139,  142,  142,   94,  457,   94,
       88,   88,  463,   94,  139,  460,   88,   94,   88,  456,
       94,   94,   94,   88,  455,   94,  517,  464,  466,  459,

       94,  461,  462,  458,  465,   88,   94,  457,  471,  139,
      469,   88,  463,  139,  460,  139,   94,   94,  139,  517,
      142,   88,   94,   88,   94,  517,  467,  464,  466,   94,
      461,  462,  468,   88,  465,  470,   88,  471,   88,   88,
       88,   94,   88,   88,  472,  142,  517,   94,  475,  142,
      473,  142,  474,   88,  142,  467,  476,   94,  139,   94,
       88,  468,   88,   88,  470,  477,  139,  139,   88,   94,
      139,   88,   94,  472,   94,   94,   94,  475,   94,   94,
      473,  479,  474,  478,  517,  476,  482,   88,  480,   94,
      483,  481,   88,  139,  142,  477,   94,   88,   94,   94,

       88,  484,  142,  142,   94,  139,  142,   94,   88,  485,
      479,   88,  478,  139,  487,  482,  517,  480,  517,  486,
      481,   88,  491,   94,   88,  488,  517,   88,   94,  142,
      139,  484,  492,   94,  139,   88,   94,  139,  489,  485,
      139,  142,  493,  487,   94,  139,  517,   94,  486,  142,
      496,  139,  491,  499,  488,  494,  501,   94,   88,  495,
       94,  139,  492,   94,  139,   88,  142,  489,  139,  502,
      142,   94,  493,  142,  517,  508,  142,  500,  506,  139,
      496,  142,  499,   88,  494,  139,  501,  142,  495,  505,
      139,  139,  509,  507,   94,  139,  517,  503,  139,  502,

      504,   94,  510,  139,  142,  512,  500,  139,  506,  517,
      513,  517,  139,  139,  139,  142,  511,  514,  505,   94,
      517,  142,  509,  507,  515,  517,  142,  142,  517,  517,
      517,  142,  510,  517,  142,  512,  516,  517,  517,  142,
      513,  517,  517,  142,  517,  511,  517,  514,  142,  142,
      142,  517,  517,  517,  515,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  516,   59,  517,   59,  517,
       59,   62,  517,   62,   62,   62,   72,  517,   72,   72,
       72,   89,  517,   89,  136,  517,  136,  140,  517,  140,
      147,  517,  147,  155,  155,  155,  155,  155,  157,  517,

      157,  157,  157,  225,  225,  225,  225,  225,  296,  296,
      296,  296,  296,  497,  517,  497,  497,  497,    3,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,

      517,  517,  517
    } ;

static yyconst flex_int16_t yy_chk[2104] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,   10,    5,    6,    6,
       12,    6,    8,    8,   17,    8,   12,   12,   15,   18,

      520,   22,   20,  508,   17,   12,   22,   12,   18,   20,
       23,   22,   23,   26,   26,   26,   26,   27,   27,   12,
       12,   28,   28,   30,   37,   72,   12,   12,   31,   39,
       33,   30,   32,   10,   12,  483,   12,   36,  391,   32,
       15,   33,   59,   30,   39,   33,  382,   30,   30,  367,
       32,   33,   31,   32,   53,   36,  360,   84,   36,   30,
       37,   30,   44,  333,   31,   39,   33,   72,   32,   32,
      320,   33,   30,   36,   39,   33,   30,   30,   35,   32,
       33,   31,   32,   34,   36,   35,   84,   36,   44,   59,
       53,   44,   34,   35,   81,  156,   81,   41,   44,   35,

      156,   34,   34,   34,  319,   35,   56,   56,  159,   56,
      296,   34,   48,   34,   35,   35,   43,   44,   40,   34,
       44,   41,   34,   35,   38,   40,   48,   43,   35,   40,
       34,   34,   34,   41,   35,  227,   38,  490,  159,   45,
       34,   42,   34,   38,   38,   40,   49,  241,   48,   38,
       41,   46,   43,   45,   40,   40,   48,   43,  225,   40,
       38,  158,   47,   45,  227,   42,   38,   49,   42,   47,
       50,   46,   38,   38,   40,   45,   46,   42,   38,  490,
       63,   64,   49,   45,   65,   50,   66,   46,   88,   89,
       93,   94,   45,   67,   42,  155,   49,   42,   47,   47,

       46,   85,   65,   68,   63,   46,   50,   67,  297,   80,
       90,   91,   66,  297,   68,   50,   63,   64,  497,   92,
       65,   91,   66,  101,   88,   89,   93,   94,   78,   67,
       61,   65,   60,   63,   58,   90,   55,   67,   95,   68,
      105,   66,   29,   92,   68,   69,   90,   91,   21,   95,
      105,   91,   14,   13,   69,   92,   69,   69,   69,  101,
      497,    9,    7,    3,   90,   96,  100,   69,   97,   69,
       69,    0,   92,   98,   95,   97,  105,  100,  103,   95,
      105,   69,    0,   96,   69,   99,   69,   69,   69,   97,
       96,   96,  102,   98,   99,  104,   69,   99,   69,   69,

        0,   96,  100,  103,   97,   97,  102,  100,  106,   98,
        0,  107,   96,  109,  103,  106,  108,  104,   97,   96,
       96,   99,   98,  111,   99,  113,  107,   99,  102,  110,
        0,  104,  103,  109,  108,  114,  102,  107,    0,  112,
      122,  120,  115,  111,  106,  106,  104,  107,  116,  109,
      119,  113,  108,  110,  117,    0,  107,  116,  118,  111,
      112,  113,  109,  108,  115,  110,  107,    0,    0,  119,
      120,  114,  111,  116,  116,  112,  122,  120,  115,  117,
      113,    0,  110,  118,  116,  127,  119,  116,  121,  112,
      117,  125,  123,  115,  118,  130,  124,    0,  119,  120,

      127,    0,  116,  116,  124,  128,  121,  123,  117,    0,
        0,  126,  118,  123,  125,  132,  136,  125,  126,    0,
      130,  127,    0,  139,  121,  131,  129,  125,  123,  128,
      127,  130,  124,  129,  124,  121,  131,  123,  140,  132,
      133,  128,  123,  125,  142,  134,  125,  126,  126,  130,
        0,  132,  136,  129,  135,  133,  137,  129,  128,  139,
      141,  131,  129,  129,    0,  135,  131,    0,  132,  134,
      137,  144,  143,  141,  140,  146,  133,  145,    0,  147,
      142,  134,  129,  148,  146,  133,  129,  150,  161,  149,
      135,  152,  137,  143,  151,  135,  141,  144,  134,  145,

      137,  193,  150,  141,  148,  151,  153,  144,  143,  149,
      154,  146,  152,  145,  146,  147,  164,  153,  160,  148,
      165,  154,  143,  150,  161,  149,  144,  152,  145,  162,
      151,  165,  150,  148,  164,  151,  162,  193,  149,  166,
      168,  152,  153,  163,  160,  167,  154,  153,  166,  170,
      163,  154,  164,    0,  160,    0,  165,  169,  205,    0,
      168,  165,    0,  164,  172,  162,  162,  170,  177,  173,
      167,  175,  172,  160,  178,  166,  168,  171,  166,  163,
      163,  167,  169,  169,  171,  170,  177,  174,  181,  168,
      173,  176,  171,  169,  205,  181,  170,  175,  174,  167,

      178,  176,    0,  176,  177,  173,  176,  175,  172,    0,
      178,  169,  169,  171,  171,  177,  176,  180,  207,  173,
      176,  179,  171,  174,  181,  181,  175,  176,  174,  178,
      183,  176,  179,  176,  185,    0,  176,  182,  184,  183,
        0,  186,  180,  187,    0,  176,  184,    0,  182,  176,
        0,  208,    0,  180,  207,  185,  188,  179,    0,  186,
      191,  187,  179,  194,  189,  195,  183,  210,  196,  183,
      185,  180,  190,  182,  184,  189,  184,  186,  182,  187,
      192,  194,  188,  190,  185,  195,  191,  208,  186,  197,
      187,  192,  188,  195,  196,    0,  191,  198,  202,  194,

      189,  195,  199,  210,  196,  189,  200,  197,  190,  201,
      194,  188,    0,  190,  195,  191,  192,    0,    0,  202,
      212,  192,  195,  196,  198,  197,  203,  212,    0,  199,
      216,  209,  200,  198,  202,  201,  197,  211,  199,  204,
      206,  203,  200,  215,    0,  201,    0,    0,  202,  209,
      204,  206,  231,  198,  213,  211,  212,  212,  199,  231,
      214,  200,  203,  213,  201,  215,  216,  209,  214,  219,
      217,  203,    0,  211,  218,  204,  206,  221,  209,  215,
      204,  206,  213,  220,  211,  223,  232,  222,  231,  231,
      213,  217,  224,  213,  215,  218,  214,  219,  214,    0,

      233,  220,  229,  221,  234,  219,  217,  228,  223,    0,
      218,  213,  222,  221,  233,  239,  224,  224,  230,  220,
      217,  223,  232,  222,  218,  242,  219,  236,  224,  234,
      220,  228,  221,  229,  237,  230,  233,  223,  229,  235,
      234,  222,  239,  228,  233,  224,  224,  240,  238,  237,
      235,  239,    0,  236,  230,  238,  244,  243,  234,  248,
      228,  242,  229,  236,  230,  245,  250,  240,  246,  247,
      237,  239,  243,    0,  250,  235,  245,  249,  251,  237,
      235,  247,  236,  240,  238,  238,  251,  244,  248,  246,
      258,  249,  244,  243,  252,  248,  240,  253,  256,  262,

      255,  245,  243,    0,  246,  247,  245,  255,  253,  254,
      250,  247,  257,  249,  252,  260,  244,  248,  246,  257,
        0,  249,  251,  262,  256,  265,  258,  254,  259,  266,
      252,  263,  264,  253,  256,  262,  255,  255,  253,  259,
      264,    0,  260,  252,  267,  254,    0,  261,  257,  257,
      265,  260,  262,  256,  261,  268,  254,  263,  261,  270,
      271,  265,  268,    0,  259,  266,  269,  263,    0,  259,
      267,  260,  273,  272,  270,  271,  264,  269,  277,  265,
      267,    0,  275,  261,  261,  274,  263,  273,  261,  276,
        0,  268,  268,  278,  274,  270,  271,  272,  281,  267,

      282,  279,  269,  280,  270,  271,    0,  269,  273,  272,
      283,  275,  279,  280,  277,  276,  281,  273,  275,  278,
      284,  274,  285,  287,  274,  276,  272,  284,  289,  278,
      286,  291,  288,  293,  281,    0,  282,  279,  295,  280,
      275,  286,  279,  280,  276,  281,  283,  287,  278,  288,
      290,  292,  294,    0,  300,    0,  284,  284,  285,  287,
      293,  290,  300,  295,  289,  299,  286,  291,  288,  293,
        0,  286,  299,    0,  295,  301,  287,  292,  288,  303,
      294,  304,  302,  305,    0,  306,  290,  292,  294,  293,
      302,  290,  295,  307,  309,  313,  310,  316,  300,  308,

      315,  299,  299,  313,  312,    0,  292,  310,  322,  294,
        0,  301,  309,  307,  335,  303,  312,  304,  302,  305,
      302,  306,  314,  308,  315,    0,    0,    0,  317,  307,
      309,  314,  310,  316,  318,  308,  315,  310,  321,  313,
      312,  309,  307,  317,  322,  323,  312,  324,  321,  318,
      335,  325,  308,  315,  326,  328,  324,  327,  314,  332,
        0,  314,  329,  323,  317,  328,  325,  332,  331,    0,
      318,    0,  326,  317,  321,    0,  327,  330,  321,  318,
      331,  323,  329,  324,  330,  334,  324,  325,  337,  336,
      326,  328,  323,  327,  339,  328,  325,  337,  329,  338,

        0,  326,    0,  332,  331,  327,  340,  334,  338,  342,
      331,  329,  343,  330,  330,  336,  344,    0,  339,    0,
      341,  334,  346,  342,  337,  336,  340,  337,  347,  341,
      339,  345,  349,  350,  348,  338,  334,  351,  338,  345,
      354,  352,  340,    0,  336,  342,  355,  339,  343,    0,
      349,  352,  344,  342,    0,  340,  341,  350,  346,  341,
      348,  351,    0,  353,  347,  354,  365,  366,  349,  350,
      348,    0,    0,  351,  356,  345,  354,  352,  353,  349,
      357,  352,  355,  358,  359,  356,  350,    0,  361,  348,
      351,  357,    0,  359,  354,  362,  363,  376,  358,  353,

      364,    0,  365,  366,  386,    0,  361,  363,  353,  368,
      356,  373,  370,  375,  372,  356,  357,    0,  369,  358,
      359,  357,  362,  359,  361,  371,  364,  368,  358,  369,
      374,  362,  363,  376,  375,  361,  364,  363,  370,  372,
      386,  377,  373,  371,  374,  368,    0,  373,  370,  375,
      372,  362,  377,  378,  369,  364,  368,  388,    0,  369,
      379,  371,  385,  375,  378,  380,  374,  370,  372,  379,
      384,  373,  371,  381,  374,  380,  383,  377,  389,  387,
      381,  384,  377,  383,    0,  390,  392,  398,  385,  378,
      387,  393,    0,  388,  378,  395,  379,  394,  385,  379,

      396,  380,    0,  399,  394,  380,  384,  405,  394,  381,
      381,  384,  383,  383,  389,  387,  393,  385,    0,  395,
      387,  390,  392,  398,  397,  396,  400,  393,  399,    0,
      401,  395,  402,  394,  394,  397,  396,  406,  394,  399,
      411,  403,  404,  405,    0,  393,    0,    0,  395,  407,
      400,  401,  403,  404,  396,  409,  407,  399,  402,  412,
      397,  410,  400,  408,  409,  397,  401,  413,  402,  414,
      408,  416,  410,  406,    0,  418,  411,  403,  404,  400,
      401,  415,  403,  404,  421,  407,  407,  402,  423,  414,
      425,  409,  426,  417,  409,  412,  418,  410,    0,  408,

      408,  415,  410,  413,  417,  414,  419,  416,  427,    0,
      420,  418,  422,    0,    0,  419,  428,  415,  414,  420,
      421,  426,  424,  422,  423,  418,  425,  429,  426,  417,
      415,  424,    0,  427,  417,  430,  432,  428,  429,  431,
      433,  434,  419,  435,  427,  419,  420,  436,  422,  420,
      426,  440,  428,  422,  437,  439,  441,    0,  424,  442,
      433,  424,  427,  429,  438,  431,  428,    0,  429,  439,
      445,  430,  432,  438,  451,  431,  433,  434,  437,  435,
      443,  444,  445,  436,  453,  442,  446,  440,  448,  433,
      437,  439,  441,  447,  431,  442,    0,  446,  448,  439,

      438,  443,  444,  438,  447,  449,  445,  437,  453,  455,
      451,  450,  445,  452,  442,  456,  443,  444,  454,    0,
      453,  459,  446,  460,  448,    0,  449,  446,  448,  447,
      443,  444,  450,  463,  447,  452,  461,  453,  458,  457,
      464,  449,  465,  466,  454,  455,    0,  450,  460,  452,
      457,  456,  458,  462,  454,  449,  461,  459,  472,  460,
      473,  450,  468,  467,  452,  462,  469,  471,  474,  463,
      470,  475,  461,  454,  458,  457,  464,  460,  465,  466,
      457,  468,  458,  467,    0,  461,  471,  477,  469,  462,
      472,  470,  476,  480,  472,  462,  473,  479,  468,  467,

      478,  476,  469,  471,  474,  481,  470,  475,  491,  478,
      468,  484,  467,  482,  480,  471,    0,  469,    0,  479,
      470,  485,  484,  477,  492,  481,    0,  486,  476,  480,
      487,  476,  485,  479,  488,  493,  478,  489,  482,  478,
      496,  481,  486,  480,  491,  495,    0,  484,  479,  482,
      489,  494,  484,  493,  481,  487,  495,  485,  499,  488,
      492,  500,  485,  486,  501,  502,  487,  482,  503,  499,
      488,  493,  486,  489,    0,  505,  496,  494,  503,  504,
      489,  495,  493,  505,  487,  506,  495,  494,  488,  502,
      509,  507,  506,  504,  499,  513,    0,  500,  510,  499,

      501,  502,  507,  511,  503,  510,  494,  512,  503,    0,
      511,    0,  515,  514,  516,  504,  509,  512,  502,  505,
        0,  506,  506,  504,  514,    0,  509,  507,    0,    0,
        0,  513,  507,    0,  510,  510,  515,    0,    0,  511,
      511,    0,    0,  512,    0,  509,    0,  512,  515,  514,
      516,    0,    0,    0,  514,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  515,  518,    0,  518,    0,
      518,  519,    0,  519,  519,  519,  521,    0,  521,  521,
      521,  522,    0,  522,  523,    0,  523,  524,    0,  524,
      525,    0,  525,  526,  526,  526,  526,  526,  527,    0,

      527,  527,  527,  528,  528,  528,  528,  528,  529,  529,
      529,  529,  529,  530,    0,  530,  530,  530,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,

      517,  517,  517
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[60] =
    {   0,
0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "lexicalAnalyzer.l"
#line 2 "lexicalAnalyzer.l"
	#include<stdio.h>
	#include<ctype.h>
	#include "y.tab.h"
#define YY_NO_INPUT 1
#line 1141 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 13 "lexicalAnalyzer.l"

#line 1359 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 518 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2019 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 14 "lexicalAnalyzer.l"
{ECHO; return START;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 15 "lexicalAnalyzer.l"
{ECHO; return END;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 16 "lexicalAnalyzer.l"
{ECHO; return S_COMMENT1;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 17 "lexicalAnalyzer.l"
{ECHO; return S_COMMENT2;}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 18 "lexicalAnalyzer.l"
{ECHO; return MULTILINE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 19 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=toupper(yytext[i]);} ECHO; return P_VARIABLE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 20 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return P_VARIABLE2;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 21 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_RESERVED;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 22 "lexicalAnalyzer.l"
{ECHO; return S_VARIABLE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 23 "lexicalAnalyzer.l"
{ECHO; return S_UNDERSCORE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 24 "lexicalAnalyzer.l"
{ECHO; return S_SEMICOLON;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 25 "lexicalAnalyzer.l"
{ECHO; return S_COMA;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 26 "lexicalAnalyzer.l"
{ECHO; return S_DOUBLEP;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 27 "lexicalAnalyzer.l"
{ECHO; return S_PARENTESIS;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 28 "lexicalAnalyzer.l"
{ECHO; return S_BRACKETS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 29 "lexicalAnalyzer.l"
{ECHO; return S_SBRACKETS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 30 "lexicalAnalyzer.l"
{ECHO; return O_CONCATENATION;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 31 "lexicalAnalyzer.l"
{ECHO; return O_CONCATENATIONA;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 32 "lexicalAnalyzer.l"
{ECHO; return S_INTERROGATION;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 33 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_CONSTANT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 34 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_CONSTANT2;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 35 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_IF;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 36 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_ELSEIF;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 37 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_ELSE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 38 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_SWITCH;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 39 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_CASE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 40 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_BREAK;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 41 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_ENDSWITCH;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 42 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_ENDIF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 43 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_WHILE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 44 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_ENDWHILE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 45 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_DO;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 46 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_FOR;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 47 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_ENDFOR;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 48 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_FOREACH;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 49 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_ENDFOREACH;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 50 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return S_FOREACH;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 51 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_INCLUDE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 52 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_CONTINUE;}	
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 53 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return W_RETURN;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 54 "lexicalAnalyzer.l"
{for(int i=11; yytext[i]; i++){yytext[i]=toupper(yytext[i]);} ECHO; return DATABASE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 55 "lexicalAnalyzer.l"
{ECHO; return O_COMPARISON;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 56 "lexicalAnalyzer.l"
{ECHO; return EQUALS;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 57 "lexicalAnalyzer.l"
{ECHO; return O_ASSIGNMENT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 58 "lexicalAnalyzer.l"
{ECHO; return O_INC_DEC;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 59 "lexicalAnalyzer.l"
{ECHO; return O_ARITHMETIC;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 60 "lexicalAnalyzer.l"
{ECHO; return O_LOGICAL;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 61 "lexicalAnalyzer.l"
{ECHO; return O_LOGICAL2;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 62 "lexicalAnalyzer.l"
{ECHO; return SYMBOLS;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 63 "lexicalAnalyzer.l"
{ECHO; return T_INTEGER;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 64 "lexicalAnalyzer.l"
{ECHO; return T_FLOAT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 65 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return T_BOOLEAN;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 66 "lexicalAnalyzer.l"
{for(int i=0; yytext[i]; i++){yytext[i]=tolower(yytext[i]);} ECHO; return T_NULL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 67 "lexicalAnalyzer.l"
{ECHO; return T_STRING;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 68 "lexicalAnalyzer.l"
{ECHO; return IDENTIFIER;}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 69 "lexicalAnalyzer.l"
{ECHO;}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 70 "lexicalAnalyzer.l"
{ECHO;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 71 "lexicalAnalyzer.l"
{return yytext[0];}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 72 "lexicalAnalyzer.l"
ECHO;
	YY_BREAK
#line 1724 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 518 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 518 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 517);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 72 "lexicalAnalyzer.l"



int yywrap() {return 1;}

